// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkforceIntegrationGateway.Infrastructure.Persistence;

#nullable disable

namespace WorkforceIntegrationGateway.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    partial class GatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkforceIntegrationGateway.Infrastructure.Persistence.RequestedDataRecord", b =>
                {
                    b.Property<Guid>("VerificationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("verification_request_id");

                    b.Property<string>("Value")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("value");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("VerificationRequestId", "Value");

                    b.HasIndex("VerificationRequestId", "Ordinal")
                        .IsUnique();

                    b.ToTable("verification_request_data", "gateway", t =>
                        {
                            t.HasCheckConstraint("ck_verification_request_data_ordinal", "ordinal BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_verification_request_data_value", "value IN ('EmploymentStatus', 'JobTitle', 'EmploymentDates')");
                        });
                });

            modelBuilder.Entity("WorkforceIntegrationGateway.Infrastructure.Persistence.VerificationRequestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_reference");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EmployeeReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("employee_reference");

                    b.Property<string>("EmployerReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("employer_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("verification_requests", "gateway", t =>
                        {
                            t.HasCheckConstraint("ck_verification_requests_client_reference", "client_reference ~ '^[A-Za-z0-9._-]{1,100}$'");

                            t.HasCheckConstraint("ck_verification_requests_employee_reference", "employee_reference ~ '^[A-Za-z0-9._-]{1,100}$'");

                            t.HasCheckConstraint("ck_verification_requests_employer_reference", "employer_reference ~ '^[A-Za-z0-9._-]{1,100}$'");

                            t.HasCheckConstraint("ck_verification_requests_status", "status = 'Pending'");
                        });
                });

            modelBuilder.Entity("WorkforceIntegrationGateway.Infrastructure.Persistence.RequestedDataRecord", b =>
                {
                    b.HasOne("WorkforceIntegrationGateway.Infrastructure.Persistence.VerificationRequestRecord", "VerificationRequest")
                        .WithMany("RequestedData")
                        .HasForeignKey("VerificationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerificationRequest");
                });

            modelBuilder.Entity("WorkforceIntegrationGateway.Infrastructure.Persistence.VerificationRequestRecord", b =>
                {
                    b.Navigation("RequestedData");
                });
#pragma warning restore 612, 618
        }
    }
}
