<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WorkforceIntegrationGateway.Application\WorkforceIntegrationGateway.Application.csproj" />
    <ProjectReference Include="..\WorkforceIntegrationGateway.Domain\WorkforceIntegrationGateway.Domain.csproj" />
  </ItemGroup>

</Project>
